name: Ein Job mit dynamischer Variable je nach Zeitplan

on:
  schedule:
    - cron: '*/5 * * * *' # jede minute
jobs:
  dynamic-message:
    runs-on: ubuntu-latest
    steps:
      - name: Setze MESSAGE je nach Zeitplan
        id: set-message
        run: |
          case "${{ github.event.schedule }}" in
            '*/5 * * * *')
              echo "message=Guten Morgen jede Minute!" >> $GITHUB_OUTPUT
              ;;
            *)
              echo "message=Unbekannter Zeitplan" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Ausgabe der Nachricht
        run: echo "${{ steps.set-message.outputs.message }}"
