# .github/workflows/secret.yml 
name: Use GitHub Secret

on:
  push:
    branches:
      - master

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret
        run: |
          echo "Using secret..."
          echo "${{secrets.MYSECRET}}" 
          echo "Secret is set: [${{ secrets.MYSECRET != '' }}]"
